// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {euint256, euint8} from "@fhevm/solidity/lib/FHE.sol";
import {ReentrancyGuard} from "solady/src/utils/ReentrancyGuard.sol";

import {AsyncHandler} from "./base/AsyncHandler.sol";
import {EInputHandler} from "./base/EInputHandler.sol";
import {Extsload} from "./base/Extsload.sol";
import {Constants} from "./helpers/Constants.sol";
import {ICardEngine} from "./interfaces/ICardEngine.sol";
import {IManagerHook, IManagerView} from "./interfaces/IManager.sol";
import {IRuleset} from "./interfaces/IRuleset.sol";
import {Action, CardEngineLib, GameData, GameStatus, PlayerData, PlayerScoreData} from "./libraries/CardEngineLib.sol";
import {ConditionalsLib} from "./libraries/ConditionalsLib.sol";
import {Card} from "./types/Card.sol";
import {Hook, HookPermissions} from "./types/Hook.sol";
import {DeckMap, PlayerStoreMap} from "./types/Map.sol";

contract CardEngine is ICardEngine, EInputHandler, AsyncHandler, ReentrancyGuard, Extsload {
    using ConditionalsLib for *;
    using Hook for IManagerHook;
    using Hook for IManagerView;

    uint256 private gId = 1; // game id counter.
    mapping(uint256 gameId => GameData) private gd; // game data mapping.

    // Errors
    error PlayerAlreadyInGame();
    error PlayerNotInGame();
    error GameAlreadyStarted();
    error GameNotStarted();
    error InvalidPlayerAddress(address addr);
    error ResolvePendingAction();
    error NotProposedPlayer(address player);
    error CannotStartGame();
    error PlayersLimitExceeded();
    error PlayersLimitNotMet();
    error CannotBootOutPlayer(address player);
    error PlayerAlreadyCommittedAction();
    error NoCommittedAction();
    error InvalidPlayerIndex();
    error CardSizeNotSupported();
    error CardDeckSizeTooSmall();
    error ZeroInitialHandSize();
    error ZeroCardDeckSize();

    // Events
    event PlayerForfeited(uint256 indexed gameId, uint256 playerIndex);
    event PlayerBootedOut(uint256 indexed gameId, uint256 playerIndex);
    event PlayerJoined(uint256 indexed gameId, address player);
    event MoveExecuted(uint256 indexed gameId, uint256 pTurnIndex, Action action);
    event GameCreated(uint256 indexed gameId, address gameCreator);
    event GameStarted(uint256 indexed gameId);
    event GameEnded(uint256 indexed gameId);
    event PlayersDealtInitialHand(uint256 indexed gameId, uint8 handSize);
    event PlayersDealt(uint256 indexed gameId, bool isPending, uint256 playerIndex, uint8 n);

    constructor() AsyncHandler() {}

    /// @dev Creates a new game with the specified parameters and returns the game ID.
    ///
    /// This function initializes the game state, including the market deck, ruleset, and proposed players.
    /// It can create a game that allows up to `params.maxPlayers` players to join, or restricts joining to
    /// a predefined list of `params.proposedPlayers`.
    ///
    /// Caller of this function is set as the game creator (manager), with hook permissions defined by `params.hookPermissions`
    /// that determines which hooks can be called during the game lifecycle.
    /// Because of how encrypted inputs are generated, it’s most likely that the caller is also the importer of the encrypted input
    /// and its proof, as generated by the relayer SDK.
    ///
    /// The ruleset must support the specified card bit size (`params.cardBitSize`) and card deck size (`params.cardDeckSize`);
    /// otherwise, the function will revert.
    /// - Card bit size is the bit width of each card in the deck. The maximum card bit size is 8 bits, while the minimum is 5 bits.
    ///   A `params.cardBitSize` value of 0 represents 8-bit, 1 represents 7-bit, and so on down to 5-bit.
    /// - The card deck size is the total number of cards in the deck. The maximum deck size is 62 cards, and the total number of cards
    ///   must be sufficient to deal the initial hand size to all players.
    ///
    /// `params.input0`, `params.input1`, and `params.inputProof` are used to initialize the encrypted market deck. If (deck size * bit size)
    /// is less than or equals 256 bits, then `params.input1` can be empty. But param.input0 cannot be empty.
    function createGame(CreateGameParams calldata params) public returns (uint256 gameId) {
        gameId = gId;
        GameData storage game = gd[gameId];
        // if proposed players is set, then max players is the length of proposed players.
        // if proposed players is not set, then max players is the max players passed in.
        uint8 numProposedPlayers = uint8(params.proposedPlayers.length);
        uint8 maxPlayers = numProposedPlayers != 0 ? numProposedPlayers : params.maxPlayers;

        if (maxPlayers > Constants.MAX_PLAYERS) revert PlayersLimitExceeded();
        if (maxPlayers < Constants.MIN_PLAYERS) revert PlayersLimitNotMet();

        for (uint256 i = 0; i < numProposedPlayers; i++) {
            address proposedPlayer = params.proposedPlayers[i];
            game.isProposedPlayer[proposedPlayer] = true;
        }

        require(params.initialHandSize != 0, ZeroInitialHandSize());
        require(params.cardDeckSize > 0, ZeroCardDeckSize());

        if (!params.gameRuleset.supportsCardSize(params.cardBitSize)) revert CardSizeNotSupported();
        game.ruleset = params.gameRuleset;

        // initialize market deck map with card size and deck size.
        DeckMap marketDeckMap = CardEngineLib.initializeMarketDeckMap(params.cardDeckSize, params.cardBitSize);
        if ((params.initialHandSize * maxPlayers) > marketDeckMap.len()) {
            revert CardDeckSizeTooSmall();
        }

        game.marketDeckMap = marketDeckMap;
        game.initialHandSize = params.initialHandSize; // set initial hand size.
        game.numProposedPlayers = numProposedPlayers;
        game.playersLeftToJoin = maxPlayers; // initially, players left to join is max players.
        game.gameCreator = msg.sender; // set `gameCreator` as msg.sender.
        game.hookPermissions = params.hookPermissions; // set initial hand size.
        game.recycleMarketDeck = params.recycleMarketDeck;

        // initialize market deck.
        euint256[2] memory marketDeck = _handleInputData(params.input0, params.input1, params.inputProof);
        game.marketDeck[0] = marketDeck[0];
        game.marketDeck[1] = marketDeck[1];

        unchecked {
            gId++;
        }

        emit GameCreated(gameId, msg.sender);
    }

    /// @dev Allows a player to join an existing game.
    ///
    /// If the proposed number of players is set during game creation, only those players can join.
    /// else, any player can join until the max players limit is reached.
    function joinGame(uint256 gameId) public nonReentrant {
        GameData storage game = gd[gameId];

        ensureGameNotStarted(game.status);

        address playerToAdd = msg.sender;
        PlayerStoreMap playerStoreMap = game.playerStoreMap;
        address gameCreator = game.gameCreator;
        // check if player is already in game.
        if (game.isPlayerActive(playerToAdd, playerStoreMap)) revert PlayerAlreadyInGame();
        // if player is not a proposed player and `proposed players` is not set, then check if max players limit has been reached.
        // if proposed players is set (i.e proposed players array > 0), then check if player is in the proposed players list.
        bool isProposedPlayer =
            game.numProposedPlayers != 0 ? game.isProposedPlayer[playerToAdd] : game.playersLeftToJoin != 0;

        if (isProposedPlayer) {
            playerStoreMap = game.addPlayer(playerToAdd, playerStoreMap);
            game.playersLeftToJoin--;
            game.playerStoreMap = playerStoreMap;
        } else {
            revert NotProposedPlayer(playerToAdd);
        }
        // - call `onJoinGame` hook.
        IManagerHook(gameCreator).onJoinGame(game.hookPermissions, gameId, playerToAdd);
        emit PlayerJoined(gameId, playerToAdd);
    }

    /// @dev Starts a game that has been created and joined by players.
    ///
    /// Starts the game if all proposed players or max players have joined. If not all players have joined, only the game
    /// creator can force start the game.
    /// Players are dealt their initial hands, and the game status is updated.
    /// Also, this triggers the `onStartGame` hook, which can potentially end the game immediately.
    function startGame(uint256 gameId) external {
        GameData storage game = gd[gameId];

        ensureGameNotStarted(game.status);

        address gameCreator = game.gameCreator;
        uint256 playersLeftToJoin = game.playersLeftToJoin;
        uint256 joined = game.playerStoreMap.len();

        // can only start game if:
        //  - `playersLeftToJoin` is zero (i.e all players have joined).
        //  - game creator is the caller and at least 2 players have joined.
        bool canStartGame;
        assembly {
            // forgefmt: disable-next-item
            canStartGame := or(iszero(playersLeftToJoin), and(eq(caller(), gameCreator), gt(joined, 0x01)))
        }
        // if game can start, all players are dealt an initial hand.
        if (!canStartGame) {
            revert CannotStartGame();
        }
        game.status = GameStatus.Started;
        game.playerTurnIdx = game.ruleset.computeStartIndex(game.playerStoreMap);

        DeckMap marketDeckMap = game.marketDeckMap;
        uint8 handSize = game.initialHandSize;

        for (uint256 i = 0; i < joined; i++) {
            // deal all players the initial hand.
            marketDeckMap = game.dealInitialHand(i, marketDeckMap, joined, handSize);
        }
        emit PlayersDealtInitialHand(gameId, handSize);

        game.marketDeckMap = marketDeckMap;
        game.lastMoveTimestamp = uint40(block.timestamp);

        emit GameStarted(gameId);

        // - call `onStartGame` hook.
        // at this point, the game might end immediately if the call to the hook returns true.
        // this is to allow the game manager to force end a game if needed (i.e if the game does not require any moves to be played).
        bool endGameAfterStart = IManagerHook(gameCreator).onStartGame(game.hookPermissions, gameId);
        finish(gameId, game, endGameAfterStart);
    }

    /// @dev Commits a move for the current player in the specified game.
    ///
    /// If a player intends to play or defend with a card, they must first commit the card so that it can be decrypted.
    ///
    /// Note: Currently, the contract does not verify that the card to commit is valid under the game rules, so the player is expected
    /// to commit the correct card, else the player's card becomes exposed.
    function commitMove(uint256 gameId, uint256 cardIndex) external {
        GameData storage game = gd[gameId];

        ensureNoCommittedAction(gameId);
        ensureGameStarted(game.status);

        uint8 currentTurnIndex = game.playerTurnIdx;
        PlayerData memory player = game.players[currentTurnIndex];

        ensureValidCaller(player.playerAddr, currentTurnIndex, game.playerStoreMap);

        // get card to commit.
        euint8 cardToCommit = game.getCardToCommit(player.deckMap, cardIndex);
        _commitMove(gameId, cardToCommit, cardIndex);
    }

    /// @dev Allows a player to clear a committed move.
    function breakCommitment(uint256 gameId) external {
        GameData storage game = gd[gameId];

        ensureGameStarted(game.status);
        uint8 currentTurnIndex = game.playerTurnIdx;
        ensureValidCaller(game.players[currentTurnIndex].playerAddr, currentTurnIndex, game.playerStoreMap);

        if (!_hasCommittedAction(gameId)) {
            revert NoCommittedAction();
        }

        _clearCommitment(gameId);
    }

    /// @dev Executes a move for the current player in the specified game.
    /// `proofData` is encoded as: abi.encode(decryptionProof, encryptedCard, decryptionResult, cardIndex)
    /// Executing a move involves resolving the player's action according to the game ruleset. Some actions require a committed move.
    /// i.e Play, Defend.
    /// The ruleset is also granted access to the player's hand, in case it needs more context.
    ///
    /// Game can end after executing a move or after a player's exit.
    function executeMove(uint256 gameId, Action action, bytes memory proofData, bytes memory extraData)
        external
        nonReentrant
    {
        GameData storage game = gd[gameId];

        uint8 playerTurnIdx = game.playerTurnIdx;
        PlayerData memory player = game.players[playerTurnIdx];
        PlayerStoreMap playerStoreMap = game.playerStoreMap;

        ensureGameStarted(game.status);
        ensureValidCaller(player.playerAddr, playerTurnIdx, playerStoreMap);

        HookPermissions hookPermissions = game.hookPermissions;
        address gameCreator = game.gameCreator;
        IRuleset ruleset = game.ruleset;
        IRuleset.ResolveMoveParams memory moveParams;
        moveParams.extraData = extraData;

        // actions {PLAY, DEFEND} require a committed move; you must commit a card before calling `executeMove`.
        // but they’re still declarative: the engine enforces nothing beyond the commitment; the ruleset decides the rest.
        // the other actions {DRAW, NEUTRAL} are purely declarative (no commit) and are interpreted by the ruleset.

        if (action.eqsOr(Action.Play, Action.Defend)) {
            {
                (, euint8 encryptedCard, bytes memory decryptionResult, uint8 cardIndex) =
                    __validateMoveDecryption(gameId, proofData);
                moveParams.card = abi.decode(decryptionResult, (Card));
                (player.deckMap, player.hand) = game.updatePlayerHand(player, playerTurnIdx, encryptedCard, cardIndex);
            }
            // check if player is eligible for a special move. this is false by default if no hook is set.
            if (ruleset.isSpecialMoveCard(moveParams.card)) {
                moveParams.isSpecial = IManagerView(gameCreator).hasSpecialMoves(
                    hookPermissions, gameId, player.playerAddr, moveParams.card, action
                );
            }
            // clean up commitment.
            _clearCommitment(gameId);
        } else {
            ensureNoCommittedAction(gameId);
        }

        moveParams.action = action;
        moveParams.pendingAction = player.pendingAction;
        moveParams.callCard = game.callCard;
        moveParams.currentPlayerIndex = playerTurnIdx;
        moveParams.playerStoreMap = playerStoreMap;
        moveParams.cardSize = game.marketDeckMap.getDeckCardSize();
        moveParams.playerDeckMap = player.deckMap;
        moveParams.playerHand = player.hand;

        CardEngineLib.grantAccessToHand(player.hand, address(ruleset));
        bool endGameAfterPlayerExit = _executeMove(gameId, game, gameCreator, hookPermissions, ruleset, moveParams);

        // call `onExecuteMove` hook with an empty card since no card is played.
        // Card(0) represents an invaild/empty card or a wild card.
        bool endGameAfterExecuteMove = IManagerHook(gameCreator).onExecuteMove(
            hookPermissions, gameId, player.playerAddr, moveParams.card, moveParams.action
        );
        // finally, check if game can end.
        finish(gameId, game, endGameAfterExecuteMove || endGameAfterPlayerExit);
    }

    /// @dev Allows a player to forfeit the game they are currently in.
    ///
    /// When a player forfeits, they are removed from the game and marked as forfeited.
    function forfeit(uint256 gameId) external nonReentrant {
        GameData storage game = gd[gameId];

        ensureGameStarted(game.status);

        uint256 playerIdx = game.playerIndex[msg.sender];
        address playerAddr = game.players[playerIdx].playerAddr;
        PlayerStoreMap playerStoreMap = game.playerStoreMap;

        ensureValidCaller(playerAddr, uint8(playerIdx), playerStoreMap);

        bool endGameAfterPlayerExit =
            _forfeit(gameId, game, playerAddr, playerIdx, playerStoreMap, game.gameCreator, game.hookPermissions);
        finish(gameId, game, endGameAfterPlayerExit);

        emit PlayerForfeited(gameId, playerIdx);
    }

    /// @dev Boots out a player from the specified game.
    ///
    /// A player can be booted out if they have exceeded the allowed delay for making a move.
    /// But this is the default condition and the game manager can override this via the `canBootOut` hook.
    /// Anyone can call this function to boot a player out if the conditions are met.
    function bootOut(uint256 gameId, uint256 playerIdx) external nonReentrant {
        GameData storage game = gd[gameId];

        ensureGameStarted(game.status);

        PlayerStoreMap playerStoreMap = game.playerStoreMap;
        if (playerStoreMap.isEmpty(playerIdx)) revert PlayerNotInGame();

        address gameCreator = game.gameCreator;
        HookPermissions hookPermissions = game.hookPermissions;
        address playerAddr = game.players[playerIdx].playerAddr;

        {
            uint40 lastMoveTimestamp = game.lastMoveTimestamp;
            uint256 phase = (lastMoveTimestamp + Constants.MAX_DELAY);
            // if a player has a committed move, max delay is extended by max decrypt time.
            if (_hasCommittedAction(gameId) && playerIdx == game.playerTurnIdx) {
                phase += Constants.MAX_DECRYPT_DELAY;
            }
            // boot out a player if their last move timestamp + MAX_DELAY(s) is less than the current block timestamp.
            // this is the default boot out condition if no hook is set.
            bool defaultCondition = phase <= block.timestamp;
            // call `canBootOut` hook to check if player can be booted out.
            // this overrides the default boot out condition of `lastMoveTimestamp + MAX_DELAY <= block.timestamp`.
            bool canBootOut = IManagerView(gameCreator).canBootOut(
                hookPermissions, gameId, playerAddr, lastMoveTimestamp, defaultCondition
            );
            if (!canBootOut) revert CannotBootOutPlayer(playerAddr);
        }

        bool endGameAfterPlayerExit =
            _forfeit(gameId, game, playerAddr, playerIdx, playerStoreMap, gameCreator, hookPermissions);
        finish(gameId, game, endGameAfterPlayerExit);

        emit PlayerBootedOut(gameId, playerIdx);
    }

    /// @dev Resolves a game.
    /// `proofData` is encoded as: abi.encode(decryptionProof, encryptedDeck, decryptionResult)
    function endGame(uint256 gameId, bytes memory proofData) external nonReentrant {
        GameData storage game = gd[gameId];
        (,, bytes memory decryptionResult) = __validateMarketDeckDecryption(gameId, proofData);
        uint256[2] memory marketDeck = abi.decode(decryptionResult, (uint256[2]));

        DeckMap marketDeckMap = game.marketDeckMap;

        uint256 playersLen = game.players.length;
        PlayerScoreData[] memory playersData = new PlayerScoreData[](playersLen);
        for (uint256 i = 0; i < playersLen; i++) {
            PlayerData memory player = game.players[i];
            Card[] memory playerHand;
            if (!player.forfeited) {
                (marketDeckMap, player.deckMap) =
                    game.resolvePending(i, marketDeckMap, player.deckMap, player.pendingAction);
                // calculate player hand.
                playerHand = CardEngineLib.getPlayerHand(player.deckMap, marketDeckMap, marketDeck);
            }
            playersData[i] = PlayerScoreData({playerAddr: player.playerAddr, deckMap: player.deckMap, hand: playerHand});
        }
        game.marketDeckMap = marketDeckMap;
        // call `onFinishGame` hook with players score data.
        IManagerHook(game.gameCreator).onFinishGame(game.hookPermissions, gameId, game.ruleset, playersData, marketDeck);
    }

    /// Checks if core conditions to end the game are met and ends the game if so.
    /// A game will end if:
    ///  - preCondition is true (i.e from a hook).
    ///  - only one player is left in the game.
    ///  - the market deck is empty.
    ///
    /// If the game ends, the market deck is committed.
    function finish(uint256 gameId, GameData storage game, bool preCondition) internal {
        bool playerStoreSingle = game.playerStoreMap.len() == 1;
        bool gameMarketDeckEmpty = game.marketDeckMap.isMapEmpty();
        bool shouldEnd;
        assembly {
            shouldEnd := or(preCondition, or(playerStoreSingle, gameMarketDeckEmpty))
        }
        if (shouldEnd) {
            ensureNoCommittedAction(gameId);
            _commitMarketDeck(gameId, game.marketDeck);
            game.status = GameStatus.Ended;
            emit GameEnded(gameId);
        }
    }

    /// If the forfeiting player is the current player, updates the turn index to the next player.
    /// Calls the `onPlayerExit` hook with `forfeited` set to true.
    function _forfeit(
        uint256 gameId,
        GameData storage game,
        address playerAddr,
        uint256 playerIdx,
        PlayerStoreMap playerStoreMap,
        address gameCreator,
        HookPermissions hookPermissions
    ) internal returns (bool) {
        playerStoreMap = playerStoreMap.removePlayer(playerIdx);
        game.players[playerIdx].forfeited = true;
        // if the forfeiting player is the current player, update the turn index to the next player.
        if (game.playerTurnIdx == playerIdx) {
            game.playerTurnIdx = game.ruleset.computeNextTurnIndex(playerStoreMap, playerIdx);
            _clearCommitment(gameId);
        }
        game.playerStoreMap = playerStoreMap;
        // - call `onPlayerExit` hook.
        return IManagerHook(gameCreator).onPlayerExit(hookPermissions, gameId, playerAddr, true);
    }

    function _executeMove(
        uint256 gameId,
        GameData storage game,
        address gameCreator,
        HookPermissions hookPermissions,
        IRuleset ruleset,
        IRuleset.ResolveMoveParams memory moveParams
    ) internal returns (bool endGameAfterPlayerExit) {
        uint8 currIdx = moveParams.currentPlayerIndex;
        // clear pending action if any.
        // if a player has a pending action, the ruleset determines whether and how it is resolved.
        if (moveParams.pendingAction != 0) {
            game.players[currIdx].pendingAction = 0;
        }
        // resolve move and get effect.
        IRuleset.Effect memory effect = ruleset.resolveMove(moveParams);
        // apply effect to game state.
        _applyEffect(gameId, game, effect, moveParams);
        PlayerData memory player = game.players[currIdx];

        if (effect.invokeAfterResolveMove) {
            moveParams.playerDeckMap = player.deckMap;
            moveParams.playerHand = player.hand;
            CardEngineLib.grantAccessToHand(moveParams.playerHand, address(ruleset));
            ruleset.afterResolveMove(moveParams);
        }

        if (player.deckMap.isMapEmpty() || effect.currentPlayerExit) {
            moveParams.playerStoreMap = moveParams.playerStoreMap.removePlayer(currIdx);
            // any player that exits the game must not have a pending action. this is expected to be handled by the ruleset.
            if (player.pendingAction != 0) {
                // player cannot exit game with a pending action.
                revert ResolvePendingAction();
            }
            game.playerStoreMap = moveParams.playerStoreMap;
            // - call `onPlayerExit` hook.
            endGameAfterPlayerExit =
                IManagerHook(gameCreator).onPlayerExit(hookPermissions, gameId, player.playerAddr, false);
        }

        emit MoveExecuted(gameId, currIdx, moveParams.action);
    }

    function _applyEffect(
        uint256 gameId,
        GameData storage game,
        IRuleset.Effect memory effect,
        IRuleset.ResolveMoveParams memory moveParams
    ) internal {
        IRuleset.Action[] memory rActions = effect.actions;
        DeckMap marketDeckMap = game.marketDeckMap;

        // apply effect against player if any.
        for (uint256 i = 0; i < rActions.length; i++) {
            uint8 op = uint8(rActions[i].op) + 1;
            bool dealPending = op > 8;
            uint8 againstPlayerIdx = rActions[i].againstPlayerIndex;

            // `PendingDeal` vs `Deal`: `PendingDeal` are `Deal` actions that are not resolved immediately, but must be resolved by
            // the ruleset at the affected player's turn.

            // if `againstPlayerIdx` is not `ALL_OTHER_PLAYERS`, then apply effect against only `againstPlayerIdx`.
            // otherwise, apply effect against all players.
            if (againstPlayerIdx != Constants.ALL_OTHER_PLAYERS) {
                if (moveParams.playerStoreMap.isEmpty(againstPlayerIdx)) {
                    revert InvalidPlayerIndex();
                }
                if (dealPending) {
                    op = op - 8;
                    // if `dealPending` is true, then the against player is dealt the pending deal.
                    game.dealPendingN(againstPlayerIdx, op);
                } else {
                    // otherwise, the against player is dealt the normal deal.
                    marketDeckMap = game.dealN(againstPlayerIdx, marketDeckMap, op);
                }
            } else {
                if (dealPending) {
                    op = op - 8;
                    // if `dealPending` is true, then all players are dealt the pending general market.
                    game.dealPendingGeneralMarket(moveParams.currentPlayerIndex, op, moveParams.playerStoreMap);
                } else {
                    // otherwise, all players are dealt the normal(non-pending) general market.
                    marketDeckMap = game.dealGeneralMarket(
                        moveParams.currentPlayerIndex, op, marketDeckMap, moveParams.playerStoreMap
                    );
                }
            }
            emit PlayersDealt(gameId, dealPending, againstPlayerIdx, op);
            game.marketDeckMap = marketDeckMap;
        }

        if (effect.togglePSMDirection) moveParams.playerStoreMap = moveParams.playerStoreMap.toggleDirection();

        // update next player turn index here.
        uint8 nextPlayer = effect.nextPlayerIndex;
        if (moveParams.playerStoreMap.isEmpty(nextPlayer)) {
            revert InvalidPlayerIndex();
        }

        game.playerTurnIdx = nextPlayer;
        game.callCard = effect.callCard;
        game.lastMoveTimestamp = uint40(block.timestamp);
    }

    /// @dev Ensures that the caller is the valid current player in the game.
    function ensureValidCaller(address currentPlayer, uint8 playerIndex, PlayerStoreMap playerStoreMap) internal view {
        if (playerStoreMap.isEmpty(playerIndex)) revert PlayerNotInGame();
        if (currentPlayer != msg.sender) revert InvalidPlayerAddress(msg.sender);
    }

    /// @dev Ensures that the game has started.
    function ensureGameStarted(GameStatus currentStatus) internal pure {
        if (currentStatus.notEqs(GameStatus.Started)) revert GameNotStarted();
    }

    /// @dev Ensures that the game has not started.
    function ensureGameNotStarted(GameStatus currentStatus) internal pure {
        if (currentStatus.notEqs(GameStatus.None)) revert GameAlreadyStarted();
    }

    /// @dev Ensures that the current player has not already committed an action.
    function ensureNoCommittedAction(uint256 gameId) internal view {
        if (_hasCommittedAction(gameId)) revert PlayerAlreadyCommittedAction();
    }
}
